// <auto-generated />
using System;
using Korp.Estoque.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estoque.API.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    partial class EstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korp.Estoque.API.Data.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f041a62-a16c-48b4-9e0c-e27c9a83761c"),
                            Ativo = true,
                            Codigo = "PRD001",
                            CriadoEm = new DateTime(2026, 4, 14, 18, 46, 53, 713, DateTimeKind.Utc).AddTicks(3222),
                            Descricao = "RTX 5090 16Gb",
                            Saldo = 150,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("f5473c19-96f7-4820-9a37-530cd1aa7eba"),
                            Ativo = true,
                            Codigo = "PRD002",
                            CriadoEm = new DateTime(2026, 4, 14, 18, 46, 53, 713, DateTimeKind.Utc).AddTicks(4323),
                            Descricao = "Samsung Galaxy S26 Pro",
                            Saldo = 8,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("a68bd204-fe4a-4f7a-bed9-dc5b04350e3c"),
                            Ativo = true,
                            Codigo = "PRD003",
                            CriadoEm = new DateTime(2026, 4, 14, 18, 46, 53, 713, DateTimeKind.Utc).AddTicks(4326),
                            Descricao = "Monitor Samsung OLED G8",
                            Saldo = 0,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("81e83bad-027a-43d5-bd27-e9ab0a5ce695"),
                            Ativo = true,
                            Codigo = "PRD004",
                            CriadoEm = new DateTime(2026, 4, 14, 18, 46, 53, 713, DateTimeKind.Utc).AddTicks(4335),
                            Descricao = "Teclado Mecânico Red Dragon",
                            Saldo = 45,
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("fcd9f749-7b66-429d-be55-032e323d907c"),
                            Ativo = true,
                            Codigo = "PRD005",
                            CriadoEm = new DateTime(2026, 4, 14, 18, 46, 53, 713, DateTimeKind.Utc).AddTicks(4337),
                            Descricao = "Mouse sem fio",
                            Saldo = 12,
                            Version = 0u
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
