FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Estoque.API.csproj", "./"]
RUN dotnet restore "Estoque.API.csproj"
COPY . .
RUN dotnet build "Estoque.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Estoque.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Estoque.API.dll"]