FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 5002

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Faturamento.API.csproj", "./"]
RUN dotnet restore "Faturamento.API.csproj"
COPY . .
RUN dotnet build "Faturamento.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Faturamento.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Faturamento.API.dll"]